name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  release:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build liimstrap image
      run: docker build -t ustclug/liimstrap:liims-2 .
        
    - name: Create rootfs file
      run: docker run --privileged --cap-add=SYS_ADMIN --rm -v /srv/dest:/srv/dest -e ROOT_PASSWORD=${{ secrets.LIIMSTRAP_ROOT_PASSWORD }} ustclug/liimstrap:liims-2
    
    - name: Pack to squashfs file
      run: docker run --privileged --cap-add=SYS_ADMIN --rm -v /srv/dest:/srv/dest -e ROOT_PASSWORD=${{ secrets.LIIMSTRAP_ROOT_PASSWORD }} -e SQUASHFS=true ustclug/liimstrap:liims-2
    
    - name: Set release tag env
      run: |
        echo "TAG_NAME=$(date +'%Y-%m-%d')_$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
        
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "/srv/dest/vmlinuz,/srv/dest/initrd.img,/srv/dest/root.sfs"
        tag: ${{ env.TAG_NAME }}
